<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Service;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $services = [
            [
                'name' => 'Web Development',
                'slug' => 'web-development',
                'short_description' => 'Transformasi digital bisnis Anda dengan website modern yang powerful, cepat, dan SEO-friendly untuk mengonversi visitor menjadi customer',
                'description' => 'Website bukan hanya soal tampilan menarik, tapi bagaimana ia bekerja untuk bisnis Anda. Kami membangun web application modern dengan teknologi terkini (React, Next.js, Laravel) yang tidak hanya cantik, tapi juga cepat, aman, dan mudah dikembangkan. Dari company profile, e-commerce, hingga dashboard kompleks—semua dirancang untuk memberikan pengalaman terbaik bagi pengguna dan hasil maksimal untuk bisnis Anda.',
                'icon' => 'code',
                'image' => null,
                'is_active' => true,
                'order' => 1,
                'why_need' => 'Di era digital, website adalah wajah pertama bisnis Anda. Website yang lambat, tidak mobile-friendly, atau sulit dinavigasi akan membuat calon customer pergi ke kompetitor. Investasi di website berkualitas adalah investasi untuk kredibilitas dan pertumbuhan bisnis jangka panjang.',
                'benefits' => [
                    ['text' => 'Meningkatkan kredibilitas dan profesionalisme brand'],
                    ['text' => 'Jangkauan customer 24/7 tanpa batasan geografis'],
                    ['text' => 'SEO optimization untuk ranking tinggi di Google'],
                    ['text' => 'Load time cepat untuk user experience optimal'],
                    ['text' => 'Responsive design untuk semua device'],
                    ['text' => 'Analytics & tracking untuk data-driven decision'],
                ],
                'workflow' => [
                    ['step' => 'Discovery & Planning - Memahami bisnis, target audience, dan goals'],
                    ['step' => 'Design & Prototyping - Wireframe dan UI/UX design mockup'],
                    ['step' => 'Development - Frontend & backend development dengan best practices'],
                    ['step' => 'Testing & QA - Cross-browser, device, dan performance testing'],
                    ['step' => 'Launch & Deployment - Setup hosting, domain, dan go-live'],
                    ['step' => 'Maintenance & Support - Monitoring, updates, dan technical support'],
                ],
                'platforms' => [
                    ['name' => 'React.js / Next.js'],
                    ['name' => 'Laravel / PHP'],
                    ['name' => 'Node.js / Express'],
                    ['name' => 'WordPress (Custom Development)'],
                    ['name' => 'Tailwind CSS / Material UI'],
                ],
                'contact_message' => 'Punya ide website yang ingin diwujudkan? Atau butuh upgrade website lama? Mari diskusi bagaimana kami bisa bantu bisnis Anda tumbuh dengan website yang powerful.',
            ],
            [
                'name' => 'Mobile Application',
                'slug' => 'mobile-application',
                'short_description' => 'Raih lebih banyak customer dengan aplikasi mobile yang intuitif, responsif, dan selalu ada di genggaman mereka',
                'description' => 'Di era mobile-first ini, bisnis yang tidak punya aplikasi mobile kehilangan peluang besar. Kami mengembangkan aplikasi iOS & Android yang tidak hanya terlihat profesional, tapi juga smooth, fast, dan user-friendly. Baik native maupun cross-platform (React Native, Flutter), kami pastikan aplikasi Anda memberikan performa terbaik dan pengalaman yang membuat pengguna betah berlama-lama.',
                'icon' => 'smartphone',
                'image' => null,
                'is_active' => true,
                'order' => 2,
                'why_need' => '80% pengguna internet mengakses dari smartphone. Aplikasi mobile memberi pengalaman lebih personal, push notification untuk engagement, dan akses offline. Ini bukan hanya trend, tapi necessity untuk bisnis yang ingin tetap relevant.',
                'benefits' => [
                    ['text' => 'Direct access - Always accessible dari home screen'],
                    ['text' => 'Push notifications untuk engagement & retention'],
                    ['text' => 'Offline functionality untuk akses tanpa internet'],
                    ['text' => 'Native features (camera, GPS, biometric)'],
                    ['text' => 'Better performance dibanding mobile web'],
                    ['text' => 'Brand presence yang lebih strong'],
                ],
                'workflow' => [
                    ['step' => 'Research & Strategy - Market analysis dan competitor study'],
                    ['step' => 'UX/UI Design - User flow, wireframe, dan visual design'],
                    ['step' => 'Development - Coding dengan agile methodology'],
                    ['step' => 'Beta Testing - Internal testing dan user acceptance test'],
                    ['step' => 'App Store Submission - Publish ke Google Play & App Store'],
                    ['step' => 'Updates & Maintenance - Bug fixes, new features, dan optimization'],
                ],
                'platforms' => [
                    ['name' => 'React Native'],
                    ['name' => 'Flutter'],
                    ['name' => 'Swift (iOS Native)'],
                    ['name' => 'Kotlin (Android Native)'],
                    ['name' => 'Firebase / AWS Amplify'],
                ],
                'contact_message' => 'Siap untuk punya aplikasi mobile sendiri? Ceritakan ide atau challenge bisnis Anda, dan kami akan carikan solusi terbaik.',
            ],
            [
                'name' => 'Desktop Application',
                'slug' => 'desktop-application',
                'short_description' => 'Otomasi workflow bisnis Anda dengan aplikasi desktop custom yang menghemat waktu dan meningkatkan produktivitas tim',
                'description' => 'Pekerjaan repetitif membuang waktu berharga tim Anda. Kami membangun desktop application yang dirancang khusus untuk kebutuhan bisnis Anda—mulai dari manajemen inventory, sistem kasir, hingga tools internal yang terintegrasi dengan sistem existing. Tersedia untuk Windows, macOS, dan Linux, aplikasi kami membantu tim bekerja lebih efisien dan fokus pada hal yang lebih penting.',
                'icon' => 'monitor',
                'image' => null,
                'is_active' => true,
                'order' => 3,
                'why_need' => 'Banyak bisnis masih bergantung pada spreadsheet dan proses manual yang prone to error. Desktop app custom memberikan automasi, validasi data, dan integrasi sistem yang tidak bisa dicapai tools generik. Ini investasi yang ROI-nya terasa langsung dalam productivity boost.',
                'benefits' => [
                    ['text' => 'Automasi task repetitif menghemat jam kerja'],
                    ['text' => 'Offline access - tidak perlu koneksi internet'],
                    ['text' => 'Better performance untuk data processing besar'],
                    ['text' => 'Custom workflow sesuai SOP perusahaan'],
                    ['text' => 'Integrasi dengan hardware (printer, scanner, dll)'],
                    ['text' => 'Data security dengan enkripsi lokal'],
                ],
                'workflow' => [
                    ['step' => 'Requirements Gathering - Deep dive ke current workflow'],
                    ['step' => 'System Design - Architecture dan database schema'],
                    ['step' => 'Prototype Development - Working prototype untuk feedback'],
                    ['step' => 'Full Development - Complete feature implementation'],
                    ['step' => 'User Training - Onboarding dan dokumentasi lengkap'],
                    ['step' => 'Deployment & Support - Installation dan ongoing maintenance'],
                ],
                'platforms' => [
                    ['name' => 'Electron (Cross-platform)'],
                    ['name' => '.NET / C# (Windows)'],
                    ['name' => 'Python / PyQt'],
                    ['name' => 'Java / JavaFX'],
                    ['name' => 'SQLite / PostgreSQL'],
                ],
                'contact_message' => 'Ada proses bisnis yang butuh otomasi? Mari diskusi bagaimana desktop app custom bisa tingkatkan efisiensi operasional Anda.',
            ],
            [
                'name' => 'Internet & Infrastructure',
                'slug' => 'internet-infrastructure',
                'short_description' => 'Infrastruktur IT yang solid adalah fondasi bisnis digital. Kami bantu setup jaringan, server, dan cloud yang aman dan scalable',
                'description' => 'Downtime server = kehilangan uang. Koneksi lambat = produktivitas drop. Kami menyediakan solusi infrastruktur lengkap: setup jaringan kantor, konfigurasi server (on-premise atau cloud), load balancing, backup strategy, hingga disaster recovery planning. Dengan monitoring 24/7 dan dokumentasi lengkap, Anda bisa tidur nyenyak karena sistem berjalan optimal.',
                'icon' => 'globe',
                'image' => null,
                'is_active' => true,
                'order' => 4,
                'why_need' => 'Infrastruktur IT yang lemah adalah bom waktu. Satu insiden bisa shut down bisnis berhari-hari. Dengan infrastructure yang proper, Anda dapat skalabilitas, reliability, dan keamanan yang bisnis modern butuhkan.',
                'benefits' => [
                    ['text' => 'High availability dengan uptime 99.9%'],
                    ['text' => 'Scalability - mudah expand sesuai growth bisnis'],
                    ['text' => 'Security hardening untuk proteksi data'],
                    ['text' => 'Automated backup & disaster recovery'],
                    ['text' => 'Network monitoring & alerting real-time'],
                    ['text' => 'Cost optimization dengan resource planning tepat'],
                ],
                'workflow' => [
                    ['step' => 'Infrastructure Assessment - Audit current setup'],
                    ['step' => 'Planning & Design - Network topology dan architecture'],
                    ['step' => 'Implementation - Setup hardware/cloud dan configuration'],
                    ['step' => 'Migration - Data transfer dengan zero downtime'],
                    ['step' => 'Testing & Optimization - Performance tuning'],
                    ['step' => 'Monitoring & Maintenance - 24/7 monitoring dan support'],
                ],
                'platforms' => [
                    ['name' => 'AWS / Google Cloud / Azure'],
                    ['name' => 'Docker / Kubernetes'],
                    ['name' => 'Nginx / Apache'],
                    ['name' => 'Cloudflare / CDN'],
                    ['name' => 'Mikrotik / Ubiquiti'],
                ],
                'contact_message' => 'Infrastruktur IT Anda butuh upgrade atau setup dari nol? Konsultasi gratis untuk diskusi kebutuhan dan solusi terbaik.',
            ],
            [
                'name' => 'Operating System Management',
                'slug' => 'operating-system',
                'short_description' => 'Instalasi, konfigurasi, dan hardening OS untuk performa maksimal dan keamanan yang ketat',
                'description' => 'Sistem operasi adalah jantung dari semua operasi IT Anda. Kami handle instalasi, konfigurasi, hardening, dan maintenance OS (Windows Server, Linux, macOS) agar sistem berjalan optimal dan aman dari ancaman. Termasuk patch management, user access control, sistem monitoring, dan dokumentasi lengkap untuk tim internal Anda.',
                'icon' => 'cpu',
                'image' => null,
                'is_active' => true,
                'order' => 5,
                'why_need' => 'OS yang tidak ter-maintain dengan baik adalah security risk terbesar. Vulnerabilities, misconfiguration, dan outdated patches bisa jadi pintu masuk hacker. Proper OS management adalah first line of defense untuk security dan stability.',
                'benefits' => [
                    ['text' => 'Security hardening sesuai best practice'],
                    ['text' => 'Automated patch management untuk up-to-date system'],
                    ['text' => 'Performance optimization untuk speed maksimal'],
                    ['text' => 'User & permission management terstruktur'],
                    ['text' => 'System logging untuk audit trail'],
                    ['text' => 'Disaster recovery preparation'],
                ],
                'workflow' => [
                    ['step' => 'System Assessment - Evaluate current OS setup'],
                    ['step' => 'Planning - Define security policies dan standards'],
                    ['step' => 'Installation/Migration - Clean install atau upgrade'],
                    ['step' => 'Hardening - Implement security configurations'],
                    ['step' => 'Documentation - Complete system documentation'],
                    ['step' => 'Ongoing Maintenance - Regular updates dan monitoring'],
                ],
                'platforms' => [
                    ['name' => 'Windows Server 2019/2022'],
                    ['name' => 'Ubuntu Server / Debian'],
                    ['name' => 'CentOS / Rocky Linux'],
                    ['name' => 'macOS Server'],
                    ['name' => 'Active Directory / LDAP'],
                ],
                'contact_message' => 'Sistem operasi Anda butuh optimization atau security audit? Kami siap bantu tingkatkan performa dan security.',
            ],
            [
                'name' => 'Graphic Design & Branding',
                'slug' => 'graphic-design',
                'short_description' => 'Brand identity yang kuat dan konsisten untuk membuat bisnis Anda mudah diingat dan stand out dari kompetitor',
                'description' => 'First impression matters. Desain visual yang profesional dan konsisten membangun kepercayaan customer. Kami menyediakan jasa design lengkap: logo design, brand guideline, social media assets, marketing materials (flyer, banner, presentation), hingga UI/UX design untuk website dan aplikasi. Semua dirancang untuk memperkuat brand identity dan menarik perhatian target market Anda.',
                'icon' => 'palette',
                'image' => null,
                'is_active' => true,
                'order' => 6,
                'why_need' => 'Brand yang tidak memorable adalah brand yang dilupakan. Desain yang konsisten dan profesional membangun recognition dan trust. Dalam pasar yang kompetitif, visual branding yang kuat adalah differentiator yang powerful.',
                'benefits' => [
                    ['text' => 'Professional brand identity yang memorable'],
                    ['text' => 'Consistency di semua touchpoint customer'],
                    ['text' => 'Increased brand recognition dan recall'],
                    ['text' => 'Stand out dari kompetitor'],
                    ['text' => 'Marketing materials yang conversion-optimized'],
                    ['text' => 'Brand guideline untuk konsistensi jangka panjang'],
                ],
                'workflow' => [
                    ['step' => 'Brand Discovery - Understand values, mission, target audience'],
                    ['step' => 'Research & Moodboard - Competitor analysis dan inspiration'],
                    ['step' => 'Concept Development - Multiple design concepts'],
                    ['step' => 'Refinement - Revisions berdasarkan feedback'],
                    ['step' => 'Finalization - File final dalam berbagai format'],
                    ['step' => 'Brand Guideline - Documentation untuk consistency'],
                ],
                'platforms' => [
                    ['name' => 'Adobe Illustrator'],
                    ['name' => 'Adobe Photoshop'],
                    ['name' => 'Figma / Adobe XD'],
                    ['name' => 'Canva Pro'],
                    ['name' => 'Adobe InDesign'],
                ],
                'contact_message' => 'Butuh refresh brand identity atau starting from scratch? Mari ciptakan visual brand yang powerful dan memorable.',
            ],
            [
                'name' => 'IT Support & Troubleshooting',
                'slug' => 'troubleshooting-cases',
                'short_description' => 'Dukungan teknis cepat dan reliable untuk menyelesaikan masalah IT sebelum mengganggu operasional bisnis',
                'description' => 'Masalah teknis bisa muncul kapan saja dan menghentikan operasional. Kami menyediakan layanan troubleshooting on-demand untuk berbagai kasus: sistem error, jaringan down, aplikasi crash, security breach, hingga recovery data. Tim kami siap diagnosa, analyze root cause, dan implement solution dengan cepat—disertai dokumentasi lengkap untuk mencegah masalah serupa terulang.',
                'icon' => 'life-buoy',
                'image' => null,
                'is_active' => true,
                'order' => 7,
                'why_need' => 'Downtime itu mahal. Setiap menit sistem down adalah revenue lost dan customer frustration. IT support yang responsive dan capable memastikan bisnis tetap running dan masalah resolved sebelum jadi bigger problem.',
                'benefits' => [
                    ['text' => 'Fast response time untuk minimize downtime'],
                    ['text' => 'Expert troubleshooting untuk berbagai tech stack'],
                    ['text' => 'Root cause analysis untuk prevent recurrence'],
                    ['text' => 'Knowledge transfer ke internal team'],
                    ['text' => 'Documentation untuk future reference'],
                    ['text' => 'Available on-demand atau retainer basis'],
                ],
                'workflow' => [
                    ['step' => 'Issue Reporting - Describe problem dan impact'],
                    ['step' => 'Initial Assessment - Quick triage dan priority'],
                    ['step' => 'Diagnosis - Deep dive investigation'],
                    ['step' => 'Solution Implementation - Apply fix dengan minimal disruption'],
                    ['step' => 'Testing & Verification - Ensure problem resolved'],
                    ['step' => 'Documentation & Follow-up - Report dan prevention tips'],
                ],
                'platforms' => [
                    ['name' => 'Windows / macOS / Linux'],
                    ['name' => 'Network Troubleshooting'],
                    ['name' => 'Web Application Debugging'],
                    ['name' => 'Database Issues'],
                    ['name' => 'Security Incidents'],
                ],
                'contact_message' => 'Punya technical issue yang butuh expert help? Hubungi kami untuk fast troubleshooting dan permanent solution.',
            ],
        ];

        foreach ($services as $service) {
            Service::create($service);
        }
    }
}
